[package]
name = "rust-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
slint = "1.7.1"
wasm-bindgen = "0.2"

[build-dependencies]
slint-build = "1.7.1"

[lib]
crate-type = ["cdylib"]

[package.metadata.wasm]
target = "web"